// Generated by CoffeeScript 1.6.3
var JavaScriptCompiler;

module.exports = JavaScriptCompiler = (function() {
  JavaScriptCompiler.prototype.brunchPlugin = true;

  JavaScriptCompiler.prototype.type = 'javascript';

  JavaScriptCompiler.prototype.extension = 'js';

  function JavaScriptCompiler(config) {
    this.config = config;
    null;
  }

  JavaScriptCompiler.prototype.compile = function(params, callback) {
    return callback(null, params);
  };

  return JavaScriptCompiler;

})();
