// Generated by CoffeeScript 1.6.2
(function() {
  var JavaScriptCompiler, capitalize, formatClassName;

  capitalize = function(string) {
    return (string[0] || '').toUpperCase() + string.slice(1);
  };

  formatClassName = function(filename) {
    return filename.split('_').map(capitalize).join('');
  };

  module.exports = JavaScriptCompiler = (function() {
    JavaScriptCompiler.prototype.brunchPlugin = true;

    JavaScriptCompiler.prototype.type = 'javascript';

    JavaScriptCompiler.prototype.extension = 'js';

    function JavaScriptCompiler(config) {
      this.config = config;
      null;
    }

    JavaScriptCompiler.prototype.compile = function(data, path, callback) {
      var error;

      try {
        return callback(null, data);
      } catch (_error) {
        error = _error;
        return callback(error);
      }
    };

    return JavaScriptCompiler;

  })();

}).call(this);
